name: Build fbs bins

on:
  push:
    branches: [ main ]

jobs:
  build_dmg:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.5.0

      - name: Build dmg
        shell: bash
        run: |
          sudo conda create -n fbs python=3.8 -y -q
          eval "$(conda shell.bash hook)"
          conda activate fbs
          sudo pip3 install pip -U
          sudo pip3 install -r requirements.txt
          fbs freeze
          fbs installer

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: SQLTranslator.dmg
          path: target/SQLTranslator.dmg

  build_exe:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.5.0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"

      - name: Build exe
        shell: powershell
        run: |
          pip3 install pip -U
          pip3 install -r requirements.txt
          fbs freeze
          fbs installer

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: SQLTranslatorSetup.exe
          path: .\target\SQLTranslatorSetup.exe

  publish:
    runs-on: ubuntu-latest
    needs: [ build_dmg, build_exe ]
    steps:
      - name: Download dmg
        uses: actions/download-artifact@v3.0.1
        with:
          name: SQLTranslator.dmg
          path: /tmp

      - name: Download exe
        uses: actions/download-artifact@v3.0.1
        with:
          name: SQLTranslatorSetup.exe
          path: /tmp

      - name: Delete Artifact
        # You may pin to the exact commit or the version.
        # uses: GeekyEggo/delete-artifact@b73cb986740e466292a536d0e32e2666c56fdeb3
        uses: GeekyEggo/delete-artifact@v2.0.0
        with:
          name: |
            SQLTranslator.dmg
            SQLTranslatorSetup.exe

      - name: Generate Prerelease Release Notes
        run: |
          zip /tmp/SQLTranslatorSetup_for_Windows.exe.zip /tmp/SQLTranslatorSetup.exe && rm /tmp/SQLTranslatorSetup.exe || ls /tmp
          mv /tmp/SQLTranslator.dmg /tmp/SQLTranslator_for_macOS.dmg
          echo '### SQLTranslator`latest`' >> ReleaseNotes.md
          echo '> Written by @ferstar with love.' >> ReleaseNotes.md
          echo '> Generated by Github Actions.' >> ReleaseNotes.md

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1.11.2
        with:
          bodyFile: ReleaseNotes.md
          artifacts: "/tmp/SQLTranslator*.*"
          tag: "v1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
